title: Alexis Enriquez
logo: /assets/img/logo.png
description: Data Science Portfolio
    <br><br>
    <a href="https://www.linkedin.com/in/alexis-enriquez-bba74b139/">View My LinkedIn Profile</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
