title: Alexis Enriquez
logo: /assets/img/logo.png
description: Data Science Portfolio
LinkedIn:
  another_url: site.https://www.linkedin.com/in/alexis-enriquez-bba74b139.url
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
